spring:
  application:
    name: devseeker

  datasource:
    url: jdbc:postgresql://localhost:5432/devseeker_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: never

  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080

jwt:
  secret: 12345678901234567890123456789012
  expiration: 3600000